# Сборка
FROM node:18 as build
WORKDIR /app
COPY client/package*.json ./
RUN npm ci
COPY client .
RUN npm run build

# Финальный образ
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html